on: push:
branches:
- master
name: Production Deploy
jobs:
FTP-Deploy-Action:
  name: FTP-Deploy-Action
  runs-on: ubuntu-latest
  steps:
  uses: actions/checkout@v2.1.0
  with:
  fetch-depth: 2
  name: FTP-Deploy-Action
  uses: Samkirkland/FTP-Deploy-Action@3.1.1
  with:
  ftp-server: sftp://access852013897.webspace-data.io
  ftp-username: u102982319
  ftp-password: $ {{secrets.prod_FTP_PASSWORD}}